"""Async PostgreSQL access layer built on asyncpg."""

from __future__ import annotations

import asyncio
import hashlib
import html
import logging
from dataclasses import dataclass
from pathlib import Path

import asyncpg

from bot.legacy import parse_legacy_dump

logger = logging.getLogger(__name__)

STATUS_DONE = "done"
STATUS_FAILED = "failed"
STATUS_CANCELLED = "cancelled"


def hash_url(url: str) -> str:
    """Stable key for the Telegram file_id cache."""
    return hashlib.sha256(url.encode("utf-8")).hexdigest()[:32]

_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT NOT NULL UNIQUE,
    username TEXT,
    registration_date TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS conversions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    status TEXT NOT NULL,
    source_platform TEXT,
    media_type TEXT,
    file_size BIGINT,
    processing_time DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS idx_conversions_telegram_id ON conversions (telegram_id);
CREATE INDEX IF NOT EXISTS idx_conversions_created_at ON conversions (created_at);
CREATE INDEX IF NOT EXISTS idx_conversions_status ON conversions (status);

-- Telegram file_id of already-uploaded media: repeated links are resent
-- instantly without downloading anything.
CREATE TABLE IF NOT EXISTS file_cache (
    url_hash TEXT NOT NULL,
    media_type TEXT NOT NULL,
    file_id TEXT NOT NULL,
    file_size BIGINT,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (url_hash, media_type)
);
-- Add description to file_cache rows created before this column existed.
ALTER TABLE file_cache ADD COLUMN IF NOT EXISTS description TEXT;

-- Admin-tunable runtime settings (upload limits, speed, solo mode, bandwidth).
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE OR REPLACE VIEW user_conversion_stats AS
SELECT
    u.telegram_id,
    u.username,
    u.registration_date,
    count(c.id) AS total_conversions,
    count(c.id) FILTER (WHERE c.status = 'done') AS done,
    count(c.id) FILTER (WHERE c.status = 'failed') AS failed,
    max(c.created_at) AS last_conversion_at
FROM users AS u
LEFT JOIN conversions AS c ON c.telegram_id = u.telegram_id
GROUP BY u.id;
"""


@dataclass(frozen=True, slots=True)
class SummaryStats:
    total_users: int
    new_users_7d: int
    total_conversions: int
    done: int
    failed: int
    conversions_24h: int


class Database:
    """Connection pool plus every query the bot needs."""

    def __init__(self, dsn: str) -> None:
        self._dsn = dsn
        self._pool: asyncpg.Pool | None = None

    @property
    def pool(self) -> asyncpg.Pool:
        if self._pool is None:
            raise RuntimeError("Database.connect() must be called before use")
        return self._pool

    async def connect(self, attempts: int = 15, delay: float = 2.0) -> None:
        """Create the pool, retrying while PostgreSQL is still starting up."""
        for attempt in range(1, attempts + 1):
            try:
                self._pool = await asyncpg.create_pool(self._dsn, min_size=1, max_size=10)
                logger.info("Connected to PostgreSQL")
                return
            except (OSError, asyncpg.PostgresError) as exc:
                if attempt == attempts:
                    raise
                logger.warning(
                    "PostgreSQL is not ready (attempt %d/%d): %s", attempt, attempts, exc
                )
                await asyncio.sleep(delay)

    async def close(self) -> None:
        if self._pool is not None:
            await self._pool.close()
            self._pool = None

    async def create_schema(self) -> None:
        await self.pool.execute(_SCHEMA)

    async def upsert_user(self, telegram_id: int, username: str | None) -> None:
        await self.pool.execute(
            """
            INSERT INTO users (telegram_id, username)
            VALUES ($1, $2)
            ON CONFLICT (telegram_id)
                -- Keep the last known @username if the user has since removed it,
                -- so we never lose a once-captured handle (NULL = no new value).
                DO UPDATE SET username = COALESCE(EXCLUDED.username, users.username)
            """,
            telegram_id,
            username,
        )

    async def add_conversion(
        self,
        telegram_id: int,
        status: str,
        source_platform: str,
        media_type: str,
        file_size: int | None = None,
        processing_time: float | None = None,
    ) -> None:
        await self.pool.execute(
            """
            INSERT INTO conversions
                (telegram_id, status, source_platform, media_type, file_size, processing_time)
            VALUES ($1, $2, $3, $4, $5, $6)
            """,
            telegram_id,
            status,
            source_platform,
            media_type,
            file_size,
            processing_time,
        )

    async def fetch_settings(self) -> dict[str, str]:
        rows = await self.pool.fetch("SELECT key, value FROM settings")
        return {row["key"]: row["value"] for row in rows}

    async def set_setting(self, key: str, value: str) -> None:
        await self.pool.execute(
            "INSERT INTO settings (key, value) VALUES ($1, $2)"
            " ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value",
            key,
            value,
        )

    async def get_cached_file(self, url_hash: str, media_type: str) -> asyncpg.Record | None:
        return await self.pool.fetchrow(
            "SELECT file_id, file_size, description FROM file_cache"
            " WHERE url_hash = $1 AND media_type = $2",
            url_hash,
            media_type,
        )

    async def store_cached_file(
        self,
        url_hash: str,
        media_type: str,
        file_id: str,
        file_size: int | None,
        description: str | None = None,
    ) -> None:
        await self.pool.execute(
            """
            INSERT INTO file_cache (url_hash, media_type, file_id, file_size, description)
            VALUES ($1, $2, $3, $4, $5)
            ON CONFLICT (url_hash, media_type)
                DO UPDATE SET file_id = EXCLUDED.file_id, file_size = EXCLUDED.file_size,
                              description = EXCLUDED.description
            """,
            url_hash,
            media_type,
            file_id,
            file_size,
            description,
        )

    async def delete_cached_file(self, url_hash: str, media_type: str) -> None:
        await self.pool.execute(
            "DELETE FROM file_cache WHERE url_hash = $1 AND media_type = $2",
            url_hash,
            media_type,
        )

    async def fetch_summary(self) -> SummaryStats:
        row = await self.pool.fetchrow(
            """
            SELECT
                (SELECT count(*) FROM users) AS total_users,
                (SELECT count(*) FROM users
                  WHERE registration_date > now() - interval '7 days') AS new_users_7d,
                count(*) AS total_conversions,
                count(*) FILTER (WHERE status = 'done') AS done,
                count(*) FILTER (WHERE status = 'failed') AS failed,
                count(*) FILTER (WHERE created_at > now() - interval '24 hours') AS conversions_24h
            FROM conversions
            """
        )
        return SummaryStats(**dict(row))

    @staticmethod
    def _user_link(telegram_id: int, username: str | None) -> str:
        """Clickable user reference: `@tag (id)`, both parts linking to the user.

        The numeric id is permanent, so its `tg://user?id=` deep link always
        works even for users who never had — or have since lost — a public
        @username; that link can never go stale. When a @username exists it is
        also shown, linked via t.me, and refreshed on every interaction (upsert).
        """
        id_link = f'<a href="tg://user?id={telegram_id}">{telegram_id}</a>'
        if not username:
            return id_link
        safe = html.escape(username, quote=True)
        tag_link = f'<a href="https://t.me/{safe}">@{html.escape(username)}</a>'
        return f"{tag_link} ({id_link})"

    @staticmethod
    def _html_page(title: str, table_header: str, table_body: str) -> str:
        return f"""<!doctype html><html lang=ru><head><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<title>{title}</title><style>
body{{font-family:system-ui,sans-serif;margin:12px;color:#1a1a1a}}
h1{{font-size:20px}}
.wrap{{overflow-x:auto}}
table{{border-collapse:collapse;font-size:13px;white-space:nowrap;width:100%}}
th,td{{padding:5px 8px;border-bottom:1px solid #e3e3e3;text-align:left}}
th{{background:#f0f0f0;position:sticky;top:0}}
.n{{text-align:right}}.ok{{color:#188038}}.fail{{color:#d93025}}.cancel{{color:#e8710a}}
</style></head><body>
<h1>{title}</h1>
<div class=wrap><table>
<tr>{table_header}</tr>
{table_body}</table></div>
</body></html>"""

    async def export_users_html(self) -> str:
        """Every user with their stats, newest registration first."""
        rows = await self.pool.fetch(
            "SELECT * FROM user_conversion_stats ORDER BY registration_date DESC"
        )
        def last_seen(row: asyncpg.Record) -> str:
            value = row["last_conversion_at"]
            return f"{value:%d.%m.%y %H:%M}" if value else "—"

        body = "".join(
            f"<tr><td>{self._user_link(row['telegram_id'], row['username'])}</td>"
            f"<td>{row['registration_date']:%d.%m.%y %H:%M}</td>"
            f"<td class=n>{row['total_conversions']}</td>"
            f"<td class='n ok'>{row['done']}</td><td class='n fail'>{row['failed']}</td>"
            f"<td>{last_seen(row)}</td></tr>"
            for row in rows
        )
        header = (
            "<th>Тег (ID)</th><th>Рег.</th>"
            "<th>Всего</th><th>✅</th><th>❌</th><th>Последняя</th>"
        )
        return self._html_page(f"👥 Пользователи ({len(rows)})", header, body)

    async def export_conversions_html(self) -> str:
        """Every conversion, newest first (by real timestamp, not insert id)."""
        rows = await self.pool.fetch(
            """
            SELECT c.*, u.username
            FROM conversions AS c
            LEFT JOIN users AS u ON u.telegram_id = c.telegram_id
            ORDER BY c.created_at DESC, c.id DESC
            """
        )
        status_class = {"done": "ok", "failed": "fail", "cancelled": "cancel"}

        def mb(row: asyncpg.Record) -> str:
            return f"{row['file_size'] / 1048576:.1f}" if row["file_size"] else "—"

        def sec(row: asyncpg.Record) -> str:
            return f"{row['processing_time']:.1f}" if row["processing_time"] else "—"

        body = "".join(
            f"<tr><td>{row['id']}</td>"
            f"<td>{self._user_link(row['telegram_id'], row['username'])}</td>"
            f"<td>{row['created_at']:%d.%m.%y %H:%M}</td>"
            f"<td class={status_class.get(row['status'], '')}>{html.escape(row['status'])}</td>"
            f"<td>{row['source_platform'] or '—'}</td><td>{row['media_type'] or '—'}</td>"
            f"<td class=n>{mb(row)}</td><td class=n>{sec(row)}</td></tr>"
            for row in rows
        )
        header = (
            "<th>#</th><th>Пользователь</th><th>Дата</th><th>Статус</th>"
            "<th>Откуда</th><th>Тип</th><th>МБ</th><th>Сек</th>"
        )
        return self._html_page(f"🎬 Конвертации ({len(rows)})", header, body)

    async def seed_from_legacy_dump(self, path: Path) -> bool:
        """Restore statistics from the old info.txt dump.

        Runs only while the users table is empty, so restarts never duplicate data.
        Returns True when an import actually happened.
        """
        if await self.pool.fetchval("SELECT count(*) FROM users"):
            return False

        users, conversions = parse_legacy_dump(path)
        if not users and not conversions:
            return False

        async with self.pool.acquire() as conn, conn.transaction():
            await conn.executemany(
                """
                INSERT INTO users (id, telegram_id, username, registration_date)
                VALUES ($1, $2, $3, $4)
                ON CONFLICT (telegram_id) DO NOTHING
                """,
                [(u.id, u.telegram_id, u.username, u.registration_date) for u in users],
            )
            await conn.executemany(
                """
                INSERT INTO conversions (id, telegram_id, created_at, status)
                VALUES ($1, $2, $3, $4)
                """,
                [(c.id, c.telegram_id, c.created_at, c.status) for c in conversions],
            )
            # Move identity sequences past the imported ids.
            await conn.execute(
                "SELECT setval(pg_get_serial_sequence('users', 'id'),"
                " (SELECT coalesce(max(id), 1) FROM users))"
            )
            await conn.execute(
                "SELECT setval(pg_get_serial_sequence('conversions', 'id'),"
                " (SELECT coalesce(max(id), 1) FROM conversions))"
            )

        logger.info(
            "Imported legacy dump: %d users, %d conversions", len(users), len(conversions)
        )
        return True
